# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-image:
    docker:
      # specify the version you desire here
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - run:
        name: authenticate with google service account
        command: |
          chmod +x .circleci/gcloud-auth.sh
          .circleci/gcloud-auth.sh

      - checkout

      # starts a remote docker environment to run docker commands
      - setup_remote_docker

      - run:
          name: build facebook-apps docker image and push image to GCR
          command: |
            gcloud auth configure-docker
            TAG=${CIRCLE_SHA1:0:9}
            docker build -t facebook-apps .
            docker tag facebook-apps eu.gcr.io/dnt-docker-registry-public/facebook-apps:latest
            docker tag facebook-apps eu.gcr.io/dnt-docker-registry-public/facebook-apps:$TAG
            docker -- push eu.gcr.io/dnt-docker-registry-public/facebook-apps:latest
            docker -- push eu.gcr.io/dnt-docker-registry-public/facebook-apps:$TAG

  deploy-to-dev:
    docker:
      - image: praqma/helmsman:v1.2.0-rc2-helm-v2.8.1
    steps:
      - checkout
      - run:
          name: run helmsman
          command: helmsman -debug -apply -f .circleci/helmsman-deployment.toml

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-image:
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only: deploy-dev
      - deploy-to-dev:
          requires:
            - build-image
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - deploy-dev
